package store

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// ReferenceInput parameter untuk add reference link.
// Salah satu dari ToSuratID atau ExternalRef harus terisi.
type ReferenceInput struct {
	ID           string // UUIDv7 generated by caller
	FromSuratID  string
	ToSuratID    *string // internal link
	ExternalRef  *string // external_ref text
	Relationship string  // enum
	Note         *string
	CreatedBy    string
}

// AddReference insert surat_references row. Verifikasi from_surat exist,
// dan to_surat_id (kalau ada) juga exist + tidak deleted.
func (s *Store) AddReference(ctx context.Context, in ReferenceInput) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("store: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Verify from_surat exist + tidak deleted
	var dummy string
	err = tx.QueryRow(ctx, `SELECT id::text FROM surat WHERE id = $1 AND NOT is_deleted`, in.FromSuratID).Scan(&dummy)
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrNotFound
	}
	if err != nil {
		return fmt.Errorf("store: check from surat: %w", err)
	}

	// Verify to_surat_id exist (kalau internal)
	if in.ToSuratID != nil && *in.ToSuratID != "" {
		err = tx.QueryRow(ctx, `SELECT id::text FROM surat WHERE id = $1 AND NOT is_deleted`, *in.ToSuratID).Scan(&dummy)
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrToSuratNotFound
		}
		if err != nil {
			return fmt.Errorf("store: check to surat: %w", err)
		}
	}

	const q = `
		INSERT INTO surat_references (id, from_surat_id, to_surat_id, relationship, external_ref, note, created_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7)`
	_, err = tx.Exec(ctx, q,
		in.ID, in.FromSuratID, in.ToSuratID, in.Relationship, in.ExternalRef, in.Note, in.CreatedBy)
	if err != nil {
		return fmt.Errorf("store: insert reference: %w", err)
	}

	return tx.Commit(ctx)
}

// DeleteReference hapus reference link. Caller harus verify from_surat owner
// di handler layer (untuk consistency dengan permission check).
func (s *Store) DeleteReference(ctx context.Context, refID, suratID string) error {
	const q = `
		DELETE FROM surat_references
		WHERE id = $1 AND from_surat_id = $2`
	tag, err := s.pool.Exec(ctx, q, refID, suratID)
	if err != nil {
		return fmt.Errorf("store: delete reference: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// ErrToSuratNotFound = referensi target tidak ada di sistem (mis. typo UUID).
var ErrToSuratNotFound = errors.New("store: target surat tidak ditemukan")
