package store

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// SuratTembusan = entry tembusan surat (instansi internal atau external_text).
type SuratTembusan struct {
	ID           string
	InstansiID   *string
	InstansiNama *string // populated kalau instansi_id non-null
	ExternalText *string
	Urutan       int
}

// TembusanInput parameter untuk insert tembusan baru.
// Salah satu dari InstansiID atau ExternalText harus terisi.
type TembusanInput struct {
	ID           string // UUIDv7 generated by caller
	SuratID      string
	InstansiID   *string
	ExternalText *string
	Urutan       int
}

// listTembusan ambil semua tembusan untuk satu surat, urut by urutan.
// Internal — dipakai GetSuratByID.
func (s *Store) listTembusan(ctx context.Context, suratID string) ([]SuratTembusan, error) {
	const q = `
		SELECT t.id::text, t.instansi_id::text, i.nama_kanonik, t.external_text, t.urutan
		FROM surat_tembusan t
		LEFT JOIN instansi i ON i.id = t.instansi_id
		WHERE t.surat_id = $1
		ORDER BY t.urutan, t.id`

	rows, err := s.pool.Query(ctx, q, suratID)
	if err != nil {
		return nil, fmt.Errorf("store: query tembusan: %w", err)
	}
	defer rows.Close()

	var out []SuratTembusan
	for rows.Next() {
		var t SuratTembusan
		var instansiID *string
		if err := rows.Scan(&t.ID, &instansiID, &t.InstansiNama, &t.ExternalText, &t.Urutan); err != nil {
			return nil, fmt.Errorf("store: scan tembusan: %w", err)
		}
		t.InstansiID = instansiID
		out = append(out, t)
	}
	return out, rows.Err()
}

// AddTembusan insert tembusan row. Verifikasi surat exist + instansi (kalau internal).
// Urutan dihitung otomatis = max(urutan)+1 kalau caller passing 0.
func (s *Store) AddTembusan(ctx context.Context, in TembusanInput) error {
	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("store: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	// Verify surat exist + tidak deleted
	var dummy string
	err = tx.QueryRow(ctx, `SELECT id::text FROM surat WHERE id = $1 AND NOT is_deleted`, in.SuratID).Scan(&dummy)
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrNotFound
	}
	if err != nil {
		return fmt.Errorf("store: check surat: %w", err)
	}

	// Verify instansi (kalau internal)
	if in.InstansiID != nil && *in.InstansiID != "" {
		err = tx.QueryRow(ctx, `SELECT id::text FROM instansi WHERE id = $1`, *in.InstansiID).Scan(&dummy)
		if errors.Is(err, pgx.ErrNoRows) {
			return ErrInstansiNotFound
		}
		if err != nil {
			return fmt.Errorf("store: check instansi: %w", err)
		}
	}

	// Auto-assign urutan kalau caller pass 0
	if in.Urutan <= 0 {
		var maxUrutan int
		err = tx.QueryRow(ctx, `SELECT COALESCE(MAX(urutan), 0) FROM surat_tembusan WHERE surat_id = $1`, in.SuratID).Scan(&maxUrutan)
		if err != nil {
			return fmt.Errorf("store: max urutan: %w", err)
		}
		in.Urutan = maxUrutan + 1
	}

	const q = `
		INSERT INTO surat_tembusan (id, surat_id, instansi_id, external_text, urutan)
		VALUES ($1, $2, $3, $4, $5)`
	_, err = tx.Exec(ctx, q, in.ID, in.SuratID, in.InstansiID, in.ExternalText, in.Urutan)
	if err != nil {
		return fmt.Errorf("store: insert tembusan: %w", err)
	}

	return tx.Commit(ctx)
}

// DeleteTembusan hapus tembusan. Caller harus verify surat owner di handler layer.
func (s *Store) DeleteTembusan(ctx context.Context, tembusanID, suratID string) error {
	const q = `DELETE FROM surat_tembusan WHERE id = $1 AND surat_id = $2`
	tag, err := s.pool.Exec(ctx, q, tembusanID, suratID)
	if err != nil {
		return fmt.Errorf("store: delete tembusan: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// ErrInstansiNotFound = instansi target tidak ada (mis. typo UUID).
var ErrInstansiNotFound = errors.New("store: instansi tidak ditemukan")
